#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "libreerp"
name = "LibreERP"
description.en = "Suite of business apps (ERP: CRM, Accounting, Point of Sale, HR, Purchases...)"
description.fr = "Une collection d'apps de gestion d'entreprise (ERP : CRM, Comptabilité, Point de Vente, RH, Achats...)"

version = "2026.06.06~ynh1"

maintainers = ["ljf"]

[upstream]
license = "LGPL-3.0-only"
website = "https://odoo.com"
demo = "https://www.odoo.com/trial"
admindoc = "https://www.odoo.com/documentation/16.0/administration.html"
userdoc = "https://www.odoo.com/documentation/16.0/applications.html"
code = "https://github.com/odoo/odoo"
cpe = "cpe:2.3:a:odoo:odoo"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true
sso = true

disk = "500M"
ram.build = "500M"
ram.runtime = "200M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.app_version]
    ask.en = "Choose the version you want"
    ask.fr = "Choisissez la version désirée"
    type = "select"
    choices = ["16", "17", "18"]
    default = "18"

    [install.lang]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["sq_AL", "am_ET", "ar_SY", "eu_ES", "bs_BA", "bg_BG", "my_MM", "ca_ES", "zh_CN", "zh_HK", "zh_TW", "hr_HR", "cs_CZ", "da_DK", "nl_BE", "nl_NL", "en_AU", "en_GB", "en_US", "et_EE", "fi_FI", "fr_BE", "fr_CA", "fr_CH", "fr_FR", "gl_ES", "ka_GE", "de_CH", "de_DE", "el_GR", "gu_IN", "he_IL", "hi_IN", "hu_HU", "id_ID", "it_IT", "ja_JP", "kab_DZ", "ko_KP", "ko_KR", "lo_LA", "lv_LV", "lt_LT", "mk_MK", "mn_MN", "nb_NO", "fa_IR", "pl_PL", "pt_BR", "pt_PT", "ro_RO", "ru_RU", "sr_RS", "sr@latin", "sk_SK", "sl_SI", "es_AR", "es_BO", "es_CL", "es_CO", "es_CR", "es_DO", "es_EC", "es_GT", "es_MX", "es_PA", "es_PE", "es_PY", "es_UY", "es_VE", "es_ES", "sv_SE", "te_IN", "th_TH", "tr_TR", "uk_UA", "vi_VN"]
    default = "en_US"

    [install.admin]
    type = "user"

    [install.admin_password]
    ask.en = "Choose a strong master admin password"
    ask.fr = "Choisissez un mot de passe maître fort pour l'administration"
    type = "password"

[resources]
    [resources.sources]

    # This one is only for the autoupdater to update correctly the version nummer, it won’t be used later
    [resources.sources.main]
    url = "https://github.com/OCA/OCB/archive/e3452b18f4a688e8797a07d2a222e46e164be48d.tar.gz"
    sha256 = "c560c171cc30e84d1c0c56008005ef8fd72c5877e7df3a75c7890270e198ac32"
    prefetch = false
    autoupdate.upstream = "https://github.com/OCA/OCB"
    autoupdate.strategy = "latest_github_commit"

    [resources.sources.main_18_oca]
    url = "https://github.com/OCA/OCB/archive/e3452b18f4a688e8797a07d2a222e46e164be48d.tar.gz"
    sha256 = "c560c171cc30e84d1c0c56008005ef8fd72c5877e7df3a75c7890270e198ac32"
    prefetch = false

    autoupdate.upstream = "https://github.com/OCA/OCB"
    autoupdate.strategy = "latest_github_commit"
    autoupdate.branch = "18.0"

    [resources.sources.main_17_oca]
    url = "https://github.com/OCA/OCB/archive/133e720cf67cc316ca4ebf75be704656035525d6.tar.gz"
    sha256 = "fa8950de05fc4b683eff84937fd209f03947d65cda4fbbc4c35d2a9819b09156"
    prefetch = false

    autoupdate.upstream = "https://github.com/OCA/OCB"
    autoupdate.strategy = "latest_github_commit"
    autoupdate.branch = "17.0"

    [resources.sources.main_16_oca]
    url = "https://github.com/OCA/OCB/archive/6423dda996ab7bd87ffa10bdb89a81d09955639c.tar.gz"
    sha256 = "036ed1285f123fde274c355766fa0908a25aa24a7b8e04c6ef88486e1b26ff44"
    prefetch = false

    autoupdate.upstream = "https://github.com/OCA/OCB"
    autoupdate.strategy = "latest_github_commit"
    autoupdate.branch = "16.0"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8069
    chat.default = 8072

    [resources.apt]
    packages = [
        "build-essential",
        "postgresql",
        "xfonts-75dpi",
        "xfonts-base",
        "gcc",
        "make",
        "libtool",
        "python3",
        "python3-pip",
        "python3-dev",
        "python3-venv",
        "python3-wheel",
        "libfreetype-dev",
        "libxml2-dev",
        "libzip-dev",
        "libsasl2-dev",
        "python3-setuptools",
        "node-less",
        "libjpeg-dev",
        "zlib1g-dev",
        "libpq-dev",
        "libxslt1-dev",
        "libldap2-dev",
        "libtiff-dev",
        "libopenjp2-7-dev",
        "libcap-dev",
        "libffi-dev",
    ]

    [resources.database]
    type = "postgresql"