#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    args.version = "14"
    args.tz = "Etc/GMT"

    # ------------
    # Tests to run
    # ------------

    test_upgrade_from.54f28204591c902ebe4a3a6b662e88e8fa598fde.name = "12.0~ynh6"
    test_upgrade_from.c82770776ccf5ea14a1b47f0ee6a113858e749e6.name = "15.0~ynh1"

[no_multisite_v15]
    args.version = "15"
    args.tz = "Etc/GMT"

[no_multisite_v16]
    args.version = "16"
    args.tz = "Etc/GMT"
