#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]
    exclude = ["change_url"]

    args.version = "16"
    args.tz = "Etc/GMT"
