#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

preinstall=0

#=================================================
# ADD SWAP
#=================================================

# if ! ynh_in_ci_tests; then
#     ynh_script_progression "Adding swap..."
#     ynh_add_swap --size=$swap_needed
# fi

#=================================================
# CREATE A POSTGRESQL DATABASE
#=================================================
ynh_script_progression "Configuring $app's PostgreSQL database..."

# Make sure that its encoding is UTF-8
ynh_psql_db_shell <<< "update pg_database set encoding = pg_char_to_encoding('UTF8') where datname = '$db_name'"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
setup_files

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building app..."

pushd "$install_dir"
    python3 -m venv venv
    venv/bin/pip3 install --upgrade pip
    venv/bin/pip3 install wheel
    venv/bin/pip3 install 'cython<3'
    venv/bin/pip3 install -r "$app/requirements.txt"
popd

#=================================================
# SETUP DATABASE
#=================================================
ynh_script_progression "Setting up the database..."

setup_database

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd
yunohost service add "$app" --log="/var/log/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start" --log_path="/var/log/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
