#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi

# Remove the dedicated systemd config
ynh_config_remove_systemd

# Remove the dedicated NGINX config
ynh_config_remove_nginx

#=================================================
# REMOVE VARIOUS FILES
#=================================================
ynh_script_progression "Removing various files..."

# Remove a directory securely
ynh_safe_rm "/etc/$app"

# Remove the log files
#REMOVEME? (Apps should not remove their log dir during remove ... this should only happen if --purge is used, and be handled by the core...) ynh_safe_rm "/var/log/$app.log"

#=================================================
# REMOVE SWAP
#=================================================

# if ! ynh_in_ci_tests; then
#     ynh_script_progression "Removing swap..."
#     ynh_del_swap
# fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
