#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# ADD SWAP
#=================================================

# if ! ynh_in_ci_tests; then
#     ynh_script_progression "Adding swap..."
#     ynh_add_swap --size=$swap_needed
# fi

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir/$appname"
ynh_restore "$install_dir/custom-addons"
ynh_restore "$install_dir/.local"

chmod -R o-rwx "$install_dir"
chown -R "$app:$app" "$install_dir"
ynh_restore "$conf_file"
chmod 400 "$conf_file"
chown "$app:$app" "$conf_file"

#=================================================
# RESTORE THE POSTGRESQL DATABASE
#=================================================
ynh_script_progression "Restoring the PostgreSQL database..."

# Make sure that its encoding is UTF-8
ynh_psql_db_shell <<< "update pg_database set encoding = pg_char_to_encoding('UTF8') where datname = '$db_name'"

# Restore the database contents
ynh_psql_db_shell < ./db.sql

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building app..."

pushd "$install_dir"
    python3 -m venv venv
    venv/bin/pip3 install --upgrade pip
    venv/bin/pip3 install wheel
    venv/bin/pip3 install -r "$appname/requirements.txt"
popd

#=================================================
# RESTORE VARIOUS FILES
#=================================================
ynh_script_progression "Restoring various files..."

ynh_restore "/var/log/$app.log"
chown "$app:$app" "/var/log/$app.log"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet
yunohost service add "$app" --log="/var/log/$app.log"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app" --action="start" --log_path="/var/log/$app.log"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
